### ISSUE TITLE
Unexpected git history rewrite

### ISSUE THREAD

**Issue by SISheogorath** [flaktack/systemd-resolved-docker#2]
👋🏻 I considered this project interesting and decided to mirror is to my infrastructure. Today the mirroring process warned me that a push failed due to a history rewrite.

A few minutes later, I figure out, that all commits after 6be3a3002274de4d64f72e6522fffd482fefebfa have been rewritten including various tags.

Not this is a problem, I just want to check with you, that this was intended behaviour and not an accident.

For comparison: 
My mirror: https://git.shivering-isles.com/github-mirror/flaktack/systemd-resolved-docker/-/commits/master
This repository: https://github.com/flaktack/systemd-resolved-docker/commits/master

**Comment by flaktack** [comment]
Thanks for getting in touch! The rewrite was intended, while I tried to figure out how the release process and related things work and to have a bit cleaner repository.

**Comment by SISheogorath** [comment]
Thanks for the info! 👍🏻  Looking forward to future work!
